### ISSUE TITLE
Edit Suggestions regarding JOSS review

### ISSUE THREAD

**Issue by prasunanand** [marouenbg/ACHR.cu#1]
Community guidelines is missing.

(PS: Will add more comments here)

**Comment by marouenbg** [comment]
Hi @prasunanand 
Thanks for the feedback. It is required to have community guidelines to: 
1)contribute to the software 2) Report issues or problems with the software 3) Seek support

I provide a feedback section and a code of conduct for contribution section in the README file. Please let me know which parts are missing.
https://github.com/marouenbg/ACHR.cu/blob/master/README.md

I am looking forward to more comments for https://github.com/openjournals/joss-reviews/issues/1363

**Comment by prasunanand** [comment]
Thanks.

Please address this:
```
 Automated tests: Are there automated tests or manual steps described so that the function of the software can be verified?
```

Is there something like `make test` ?

**Comment by marouenbg** [comment]
Hi @prasunanand, yes I have continuous integration deployed on github through Travis. I have 82% of the code covered.
https://github.com/marouenbg/ACHR.cu/blob/master/travis/build-run.sh

**Comment by prasunanand** [comment]
Cool.

Can you add this as a `make test` task and mention it in README ? This helps the user to ensure that the installation was successful and the functionality is right .

**Comment by marouenbg** [comment]
Great comment. I added a make test at the root of VFWarmup and ACHRcu. I also added a description in README. I hope this corresponds to what you had in mind.
Check commit https://github.com/marouenbg/ACHR.cu/commit/9ffca28425a06215ed03f5ba42f56bb810960e5a and 55980e895846efc8894c77ed99e7720f94b1f1ed

**Comment by prasunanand** [comment]
Hi,

can you provide me access to codeocean capsule?
email : prasunanand.bitsp@gmail.com

**Comment by marouenbg** [comment]
yes, here is the public link https://codeocean.com/capsule/2291048/tree/v1 (broken link fixed in  README)
